name: mern-app

services:
  api:
    build:
      context: ./server
      target: production
    restart: unless-stopped 
    env_file: ./server/.env
    networks:
      - mern-app

  client:
    build:
      context: ./client
      target: production
      args:
        - VITE_APP_BACKEND_SERVER_URL= http://api.${DOMAIN_NAME}
    restart: unless-stopped 
    env_file: ./client/.env
    # volumes:
    #   - ./client:/app #mount client code to app container
    #   - /app/node_modules #ignore node_modules in container
    networks:
      - mern-app
    # ports:
    #   - 3000:3000
    depends_on:
      - api

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
        - 80:80
        - 443:443
    environment:
         DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
        - caddy_data:/data
        - caddy_config:/config
    networks:
        - mern-app
    depends_on:
        - client
        - api
        
        
networks:
  mern-app:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
