name: mern-app

services:
  api:
    build:
      context: ./server
      target: production
    restart: unless-stopped 
    env_file: ./server/.env
    networks:
      - mern-app

  client:
    build:
      context: ./client
      target: production
      args:
        - VITE_APP_BACKEND_SERVER_URL=https://mern-todo-app-api.ramtinba.de 
    restart: unless-stopped 
    env_file: ./client/.env
    networks:
      - mern-app
    depends_on:
      - api

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
        - 80:80
        - 443:443
    environment:
         DOMAIN_NAME: https://mern-todo-app-api.ramtinba.de
    volumes:
        - caddy_data:/data
        - caddy_config:/config
    networks:
        - mern-app
    depends_on:
        - client
        - api
        
        
networks:
  mern-app:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
